server:
  port: 7403

# redis--lettuce
spring:
  datasource:
    url: jdbc:mysql://192.168.229.129:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    # 最小空闲连接数
    username: yazheng
    password: yazheng123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      # 最小空闲连接数
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 100
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      hikari.max-lifetime: 1800000
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #用作数据库
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.229.129
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: rootadmin
    # 连接超时时间（毫秒）
    timeout: 200
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认8
        max-active: 8
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1
  #redis用作缓存
  cache:
   # 则是配置缓存名称，多个名称可以使用逗号分隔，以便于缓存注解的引用
    cache-names: userCache
    #缓存类型
    type: redis
    redis:
      #缓存超时时间,单位ms
      time-to-live: 1800000

mybatis:
  configuration:
    #下划线转驼峰命名
    map-underscore-to-camel-case: true