server:
  port: 7403

# redis--lettuce
spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    host: 192.168.229.129
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: rootadmin
    # 连接超时时间（毫秒）
    timeout: 200
    lettuce:
      pool:
        #连接池最大连接数（使用负值表示没有限制） 默认8
        max-active: 8
        # 连接池中的最大空闲连接 默认8
        max-idle: 8
        # 连接池中的最小空闲连接 默认0
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1