server:
  port: 7402
spring:
  security:
    user:
      password: 111
      name: cuining
    secrit: xxxx

  #数据源默认是hikari
  datasource:
    url: jdbc:mysql://192.168.229.129:3306/springboot?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    # 最小空闲连接数
    username: yazheng
    password: yazheng123
    driver-class-name: com.mysql.cj.jdbc.Driver