spring:
  datasource:
    db01:
      username: root01
      password: root01
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.229.128:3306/db01?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      min-pool-size: 3
      max-pool-size: 25
      max-life-time: 20000
      borrow-connectin-timeout: 30
      maxi-idle-time: 60
      maintenance-interval: 60
      login-timeout: 30
      testQuery: select 1
    db02:
      username: root02
      password: root02
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.229.131:3306/db02?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
      min-pool-size: 3
      max-pool-size: 25
      max-life-time: 20000
      borrow-connectin-timeout: 30
      maxi-idle-time: 60
      maintenance-interval: 60
      login-timeout: 30
      testQuery: select 1

